# Generated by Django 5.0.4 on 2024-05-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='productoImg',
            field=models.ImageField(upload_to='productoimg/'),
        ),
    ]
