# Generated by Django 5.0.4 on 2024-05-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_productoimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
    ]
