# Generated by Django 5.0.4 on 2024-05-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_productodescripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='productoImg',
            field=models.ImageField(blank=True, null=True, upload_to='productoimg/'),
        ),
    ]
